export const metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy for Keposting",
};

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12 text-slate-800">
      <h1 className="text-3xl font-bold mb-2">Privacy Policy</h1>
      <p className="text-sm text-slate-500 mb-8">Effective: 8 August 2026</p>

      <div className="space-y-6 prose prose-slate max-w-none">
        <section>
          <h2 className="text-xl font-semibold">1. Introduction</h2>
          <p>
            This Privacy Policy explains how Keposting collects, uses, and protects your
            information when you use our service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">2. Information We Collect</h2>
          <p>We collect the following data:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>
              <strong>Account information</strong>: email address, password (hashed)
            </li>
            <li>
              <strong>Business profile</strong>: business name, industry, location, target
              customer, and other information you provide during onboarding
            </li>
            <li>
              <strong>Uploaded content</strong>: product photos, logos, other images you upload
            </li>
            <li>
              <strong>Generated content</strong>: images and captions generated by the AI
            </li>
            <li>
              <strong>Usage data</strong>: token usage, feature access, error logs
            </li>
            <li>
              <strong>Payment data</strong>: handled by our payment providers (Lemon Squeezy,
              Midtrans) — we do not store your credit card details on our servers
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold">3. How We Use Your Data</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>To provide and improve the Service</li>
            <li>To generate content according to your requests</li>
            <li>To send account-related notifications (verification, password reset, etc.)</li>
            <li>To debug and monitor Service performance</li>
            <li>To respond to your support requests</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold">4. Third-Party Services</h2>
          <p>We share limited data with the following third parties to provide the Service:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>
              <strong>Supabase</strong> (database and storage) — stores your account data and
              content
            </li>
            <li>
              <strong>Vercel</strong> (hosting) — hosts our application
            </li>
            <li>
              <strong>Google Gemini</strong> and <strong>OpenAI</strong> (AI providers) —
              receive your business profile, prompts, and uploaded photos to generate content
            </li>
            <li>
              <strong>Lemon Squeezy</strong> and <strong>Midtrans</strong> (payment) — receive
              payment information for token purchases
            </li>
            <li>
              <strong>Mailspace</strong> (email) — sends transactional emails
            </li>
          </ul>
          <p>
            We do not sell your data to third parties for advertising purposes.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">5. Data Retention</h2>
          <p>
            We retain your data while your account is active. If you request account deletion,
            we will remove your personal data within 30 days, except where retention is
            required by law (e.g., payment records).
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">6. Your Rights</h2>
          <p>You have the right to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Access the personal data we hold about you</li>
            <li>Correct inaccurate data</li>
            <li>Request deletion of your account and data</li>
            <li>Export your data in a portable format</li>
          </ul>
          <p>
            To exercise these rights, email{" "}
            <a href="mailto:info@keposting.com" className="text-teal-600 underline">
              info@keposting.com
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">7. Cookies</h2>
          <p>
            We use essential cookies to keep you logged in and to remember your language
            preference. We do not use tracking cookies for advertising.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">8. Data Security</h2>
          <p>
            We use industry-standard encryption (HTTPS, encrypted database connections) to
            protect your data. However, no method of transmission over the internet is 100%
            secure — we cannot guarantee absolute security.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">9. Children</h2>
          <p>
            The Service is not intended for users under the age of 13. We do not knowingly
            collect data from children.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">10. International Transfers</h2>
          <p>
            Your data may be processed in countries outside your own, including where our
            service providers operate. We ensure appropriate safeguards are in place for these
            transfers.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">11. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. We will notify you of material
            changes via email or in-app.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">12. Contact</h2>
          <p>
            Questions about this Privacy Policy:{" "}
            <a href="mailto:info@keposting.com" className="text-teal-600 underline">
              info@keposting.com
            </a>
          </p>
        </section>
      </div>
    </main>
  );
}
