import type { Template } from "./types";
import { defaultBrand } from "./brand";

export const edukasiTemplate: Template = {
  id: "edukasi",
  name: "Edukasi / Tips",
  canvas: { width: 1080, height: 1350 },
  brand: { ...defaultBrand, backgroundColor: "#ffffff" },
  slots: [
    {
      id: "title",
      type: "text",
      box: { x: 60, y: 140, width: 960, height: 90 },
      fontFamily: "Inter",
      maxFontSize: 44,
      minFontSize: 30,
      maxLines: 2,
      align: "left",
      color: "#0f172a",
      fontWeight: 800,
      label: "Judul",
      placeholder: "5 Tips Menjaga Kesehatan Gigi",
    },
    {
      id: "tip1",
      type: "text",
      box: { x: 60, y: 280, width: 960, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 28,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 500,
      label: "Tip 1",
      placeholder: "1. Sikat gigi dua kali sehari",
    },
    {
      id: "tip2",
      type: "text",
      box: { x: 60, y: 365, width: 960, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 28,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 500,
      label: "Tip 2",
      placeholder: "2. Kurangi makanan manis",
    },
    {
      id: "tip3",
      type: "text",
      box: { x: 60, y: 450, width: 960, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 28,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 500,
      label: "Tip 3",
      placeholder: "3. Rutin periksa ke dokter gigi",
    },
    {
      id: "tip4",
      type: "text",
      box: { x: 60, y: 535, width: 960, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 28,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 500,
      label: "Tip 4",
      placeholder: "4. Ganti sikat gigi tiap 3 bulan",
    },
    {
      id: "tip5",
      type: "text",
      box: { x: 60, y: 620, width: 960, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 28,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 500,
      label: "Tip 5",
      placeholder: "5. Perbanyak minum air putih",
    },
    {
      id: "photo",
      type: "image",
      box: { x: 60, y: 730, width: 960, height: 420 },
      fit: "cover",
      borderRadius: 24,
      label: "Foto",
      placeholder: "https://...",
    },
  ],
};
