import type { Template, TemplateLayout } from "./types";
import { defaultBrand } from "./brand";

const layout45: TemplateLayout = {
  canvas: { width: 1080, height: 1350 },
  logo: { x: 984, y: 32, size: 40 },
  footerLayout: {
    x: 60,
    y: 1280,
    direction: "row",
    gap: 20,
    iconSize: 32,
    textSize: 20,
    textColor: "#64748b",
    nameColor: "#0f172a",
  },
  slots: [
    {
      id: "title",
      type: "text",
      box: { x: 60, y: 140, width: 880, height: 100 },
      fontFamily: "Inter",
      maxFontSize: 48,
      minFontSize: 32,
      maxLines: 2,
      align: "left",
      color: "#0f172a",
      fontWeight: 800,
      label: "Judul",
      placeholder: "5 Tips Menjaga Kesehatan Gigi",
    },
    {
      id: "tip1",
      type: "text",
      box: { x: 60, y: 290, width: 960, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 32,
      minFontSize: 24,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 500,
      label: "Tip 1",
      placeholder: "1. Sikat gigi dua kali sehari",
    },
    {
      id: "tip2",
      type: "text",
      box: { x: 60, y: 380, width: 960, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 32,
      minFontSize: 24,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 500,
      label: "Tip 2",
      placeholder: "2. Kurangi makanan manis",
    },
    {
      id: "tip3",
      type: "text",
      box: { x: 60, y: 470, width: 960, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 32,
      minFontSize: 24,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 500,
      label: "Tip 3",
      placeholder: "3. Rutin periksa ke dokter gigi",
    },
    {
      id: "tip4",
      type: "text",
      box: { x: 60, y: 560, width: 960, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 32,
      minFontSize: 24,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 500,
      label: "Tip 4",
      placeholder: "4. Ganti sikat gigi tiap 3 bulan",
    },
    {
      id: "tip5",
      type: "text",
      box: { x: 60, y: 650, width: 960, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 32,
      minFontSize: 24,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 500,
      label: "Tip 5",
      placeholder: "5. Perbanyak minum air putih",
    },
    {
      id: "photo",
      type: "image",
      box: { x: 60, y: 750, width: 960, height: 460 },
      fit: "contain",
      borderRadius: 24,
      label: "Foto",
    },
  ],
};

export const edukasiTemplate: Template = {
  id: "edukasi",
  name: "Edukasi / Tips",
  brand: { ...defaultBrand, backgroundColor: "#ffffff" },
  layouts: {
    "4:5": layout45,
    "1:1": { ...layout45, canvas: { width: 1080, height: 1080 } },
    "9:16": { ...layout45, canvas: { width: 1080, height: 1920 } },
  },
};
