import type { Template } from "./types";
import { defaultBrand } from "./brand";

export const eventTemplate: Template = {
  id: "event",
  name: "Event / Acara",
  canvas: { width: 1080, height: 1350 },
  brand: { ...defaultBrand, backgroundColor: "#0f172a" },
  slots: [
    {
      id: "title",
      type: "text",
      box: { x: 60, y: 150, width: 960, height: 140 },
      fontFamily: "Inter",
      maxFontSize: 52,
      minFontSize: 32,
      maxLines: 2,
      align: "left",
      color: "#ffffff",
      fontWeight: 800,
      label: "Judul Acara",
      placeholder: "Seminar Kesehatan Keluarga",
    },
    {
      id: "datetime",
      type: "text",
      box: { x: 60, y: 310, width: 960, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 32,
      minFontSize: 24,
      maxLines: 1,
      align: "left",
      color: "#facc15",
      fontWeight: 700,
      label: "Tanggal & Waktu",
      placeholder: "Sabtu, 15 Agustus 2026 · 09.00 WIB",
    },
    {
      id: "location",
      type: "text",
      box: { x: 60, y: 380, width: 960, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 26,
      minFontSize: 20,
      maxLines: 2,
      align: "left",
      color: "#e2e8f0",
      fontWeight: 400,
      label: "Lokasi",
      placeholder: "Aula Klinik Sehat Sentosa, Jl. Melati No. 10",
    },
    {
      id: "photo",
      type: "image",
      box: { x: 60, y: 470, width: 960, height: 500 },
      fit: "cover",
      borderRadius: 24,
      label: "Foto",
      placeholder: "https://...",
    },
    {
      id: "cta",
      type: "text",
      box: { x: 60, y: 1000, width: 960, height: 70 },
      fontFamily: "Inter",
      maxFontSize: 30,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#facc15",
      fontWeight: 700,
      label: "Ajakan Bertindak (CTA)",
      placeholder: "Daftar sekarang via WA →",
    },
  ],
};
