import type { Template } from "./types";
import { defaultBrand } from "./brand";

export const produkTemplate: Template = {
  id: "produk",
  name: "Produk / Menu",
  canvas: { width: 1080, height: 1350 },
  brand: { ...defaultBrand, backgroundColor: "#ffffff" },
  slots: [
    {
      id: "productImage",
      type: "image",
      box: { x: 60, y: 140, width: 960, height: 560 },
      fit: "cover",
      borderRadius: 24,
      label: "Foto Produk",
      placeholder: "https://...",
    },
    {
      id: "productName",
      type: "text",
      box: { x: 60, y: 730, width: 960, height: 70 },
      fontFamily: "Inter",
      maxFontSize: 40,
      minFontSize: 28,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 800,
      label: "Nama Produk",
      placeholder: "Ayam Geprek Sambal Bawang",
    },
    {
      id: "price",
      type: "text",
      box: { x: 60, y: 810, width: 960, height: 70 },
      fontFamily: "Inter",
      maxFontSize: 40,
      minFontSize: 28,
      maxLines: 1,
      align: "left",
      color: "#2563eb",
      fontWeight: 800,
      label: "Harga",
      placeholder: "Rp18.000",
    },
    {
      id: "description",
      type: "text",
      box: { x: 60, y: 890, width: 960, height: 150 },
      fontFamily: "Inter",
      maxFontSize: 26,
      minFontSize: 20,
      maxLines: 3,
      align: "left",
      color: "#475569",
      fontWeight: 400,
      label: "Deskripsi",
      placeholder: "Ayam crispy dengan sambal bawang pedas, disajikan hangat bersama nasi.",
    },
  ],
};
