import type { Template } from "./types";
import { defaultBrand } from "./brand";

export const profilTemplate: Template = {
  id: "profil",
  name: "Profil / Perkenalan",
  canvas: { width: 1080, height: 1350 },
  brand: { ...defaultBrand, backgroundColor: "#ffffff" },
  slots: [
    {
      id: "photo",
      type: "image",
      box: { x: 60, y: 140, width: 960, height: 500 },
      fit: "cover",
      borderRadius: 24,
      label: "Foto",
      placeholder: "https://...",
    },
    {
      id: "name",
      type: "text",
      box: { x: 60, y: 660, width: 960, height: 70 },
      fontFamily: "Inter",
      maxFontSize: 44,
      minFontSize: 30,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 800,
      label: "Nama",
      placeholder: "dr. Andi Wijaya",
    },
    {
      id: "role",
      type: "text",
      box: { x: 60, y: 740, width: 960, height: 50 },
      fontFamily: "Inter",
      maxFontSize: 26,
      minFontSize: 20,
      maxLines: 1,
      align: "left",
      color: "#2563eb",
      fontWeight: 600,
      label: "Peran / Jabatan",
      placeholder: "Dokter Umum",
    },
    {
      id: "description",
      type: "text",
      box: { x: 60, y: 810, width: 960, height: 180 },
      fontFamily: "Inter",
      maxFontSize: 24,
      minFontSize: 18,
      maxLines: 4,
      align: "left",
      color: "#475569",
      fontWeight: 400,
      label: "Deskripsi Singkat",
      placeholder: "Berpengalaman lebih dari 10 tahun melayani pasien dengan pendekatan yang ramah dan komunikatif.",
    },
  ],
};
