import type { Template, TemplateLayout } from "./types";
import { defaultBrand } from "./brand";

const layout45: TemplateLayout = {
  canvas: { width: 1080, height: 1350 },
  logo: { x: 976, y: 34, size: 64 },
  footerLayout: {
    x: 700,
    y: 1190,
    direction: "column",
    align: "flex-end",
    gap: 14,
    iconSize: 44,
    textSize: 24,
    textColor: "#475569",
    nameColor: "#0f172a",
  },
  decorations: [
    {
      box: { x: -200, y: -260, width: 900, height: 900 },
      shape: "rect",
      color: "#2563eb",
      opacity: 0.08,
      rotateDeg: -18,
    },
    {
      box: { x: 620, y: -120, width: 560, height: 560 },
      shape: "circle",
      color: "#facc15",
      opacity: 0.18,
    },
  ],
  slots: [
    {
      id: "promoLabel",
      type: "text",
      box: { x: 60, y: 150, width: 500, height: 50 },
      fontFamily: "Inter",
      maxFontSize: 30,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#2563eb",
      fontWeight: 700,
      label: "Label Promo",
      placeholder: "PROMO AKHIR BULAN",
    },
    {
      id: "title",
      type: "text",
      box: { x: 60, y: 200, width: 960, height: 100 },
      fontFamily: "Inter",
      maxFontSize: 50,
      minFontSize: 32,
      maxLines: 2,
      align: "left",
      color: "#0f172a",
      fontWeight: 700,
      label: "Nama Penawaran",
      placeholder: "Paket Hemat Perawatan Rutin",
    },
    {
      id: "price",
      type: "text",
      box: { x: 60, y: 320, width: 960, height: 170 },
      fontFamily: "Inter",
      maxFontSize: 104,
      minFontSize: 60,
      maxLines: 1,
      align: "left",
      color: "#2563eb",
      fontWeight: 800,
      label: "Harga",
      placeholder: "Rp99.000",
    },
    {
      id: "productImage",
      type: "image",
      box: { x: 60, y: 500, width: 960, height: 480 },
      fit: "contain",
      borderRadius: 24,
      label: "Foto Produk",
    },
    {
      id: "cta",
      type: "text",
      box: { x: 60, y: 1000, width: 960, height: 70 },
      fontFamily: "Inter",
      maxFontSize: 34,
      minFontSize: 26,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 700,
      label: "Ajakan Bertindak (CTA)",
      placeholder: "Pesan sekarang via WA →",
    },
  ],
};

export const promoTemplate: Template = {
  id: "promo",
  name: "Promo Harga",
  brand: { ...defaultBrand, backgroundColor: "#ffffff" },
  layouts: {
    "4:5": layout45,
    "1:1": { ...layout45, canvas: { width: 1080, height: 1080 } },
    "9:16": { ...layout45, canvas: { width: 1080, height: 1920 } },
  },
};
