import type { Template } from "./types";
import { defaultBrand } from "./brand";

export const promoTemplate: Template = {
  id: "promo",
  name: "Promo Harga",
  canvas: { width: 1080, height: 1350 },
  brand: { ...defaultBrand, backgroundColor: "#ffffff" },
  slots: [
    {
      id: "promoLabel",
      type: "text",
      box: { x: 60, y: 140, width: 400, height: 50 },
      fontFamily: "Inter",
      maxFontSize: 28,
      minFontSize: 20,
      maxLines: 1,
      align: "left",
      color: "#2563eb",
      fontWeight: 700,
      label: "Label Promo",
      placeholder: "PROMO AKHIR BULAN",
    },
    {
      id: "title",
      type: "text",
      box: { x: 60, y: 190, width: 960, height: 100 },
      fontFamily: "Inter",
      maxFontSize: 44,
      minFontSize: 28,
      maxLines: 2,
      align: "left",
      color: "#0f172a",
      fontWeight: 700,
      label: "Nama Penawaran",
      placeholder: "Paket Hemat Perawatan Rutin",
    },
    {
      id: "price",
      type: "text",
      box: { x: 60, y: 310, width: 960, height: 160 },
      fontFamily: "Inter",
      maxFontSize: 96,
      minFontSize: 56,
      maxLines: 1,
      align: "left",
      color: "#2563eb",
      fontWeight: 800,
      label: "Harga",
      placeholder: "Rp99.000",
    },
    {
      id: "productImage",
      type: "image",
      box: { x: 60, y: 490, width: 960, height: 480 },
      fit: "cover",
      borderRadius: 24,
      label: "Foto Produk",
      placeholder: "https://...",
    },
    {
      id: "cta",
      type: "text",
      box: { x: 60, y: 1000, width: 960, height: 70 },
      fontFamily: "Inter",
      maxFontSize: 32,
      minFontSize: 24,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 700,
      label: "Ajakan Bertindak (CTA)",
      placeholder: "Pesan sekarang via WA →",
    },
  ],
};
