import type { Template } from "./types";
import { defaultBrand } from "./brand";

export const rekrutmenTemplate: Template = {
  id: "rekrutmen",
  name: "Rekrutmen / Lowongan",
  canvas: { width: 1080, height: 1350 },
  brand: { ...defaultBrand, backgroundColor: "#0f172a" },
  slots: [
    {
      id: "title",
      type: "text",
      box: { x: 60, y: 140, width: 960, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 36,
      minFontSize: 28,
      maxLines: 1,
      align: "left",
      color: "#facc15",
      fontWeight: 800,
      label: "Judul",
      placeholder: "OPEN RECRUITMENT",
    },
    {
      id: "intro",
      type: "text",
      box: { x: 60, y: 210, width: 960, height: 90 },
      fontFamily: "Inter",
      maxFontSize: 26,
      minFontSize: 20,
      maxLines: 2,
      align: "left",
      color: "#e2e8f0",
      fontWeight: 400,
      label: "Kalimat Pembuka",
      placeholder: "Kami sedang mencari talenta terbaik untuk bergabung bersama tim kami.",
    },
    {
      id: "position1",
      type: "text",
      box: { x: 60, y: 320, width: 960, height: 50 },
      fontFamily: "Inter",
      maxFontSize: 28,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#ffffff",
      fontWeight: 600,
      label: "Posisi 1",
      placeholder: "Admin Pelayanan",
    },
    {
      id: "position2",
      type: "text",
      box: { x: 60, y: 380, width: 960, height: 50 },
      fontFamily: "Inter",
      maxFontSize: 28,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#ffffff",
      fontWeight: 600,
      label: "Posisi 2",
      placeholder: "Perawat Pelaksana",
    },
    {
      id: "position3",
      type: "text",
      box: { x: 60, y: 440, width: 960, height: 50 },
      fontFamily: "Inter",
      maxFontSize: 28,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#ffffff",
      fontWeight: 600,
      label: "Posisi 3",
      placeholder: "Staf Kebersihan",
    },
    {
      id: "position4",
      type: "text",
      box: { x: 60, y: 500, width: 960, height: 50 },
      fontFamily: "Inter",
      maxFontSize: 28,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#ffffff",
      fontWeight: 600,
      label: "Posisi 4",
      placeholder: "Satpam",
    },
    {
      id: "photo",
      type: "image",
      box: { x: 60, y: 570, width: 960, height: 460 },
      fit: "cover",
      borderRadius: 24,
      label: "Foto",
      placeholder: "https://...",
    },
    {
      id: "cta",
      type: "text",
      box: { x: 60, y: 1050, width: 960, height: 70 },
      fontFamily: "Inter",
      maxFontSize: 30,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#facc15",
      fontWeight: 700,
      label: "Kontak",
      placeholder: "Kirim CV ke WA 0812-0000-0000",
    },
  ],
};
