import type { Template, TemplateLayout } from "./types";
import { defaultBrand } from "./brand";

const layout45: TemplateLayout = {
  canvas: { width: 1080, height: 1350 },
  logo: { x: 508, y: 34, size: 64 },
  footerLayout: {
    x: 60,
    y: 1080,
    direction: "column",
    gap: 16,
    iconSize: 44,
    textSize: 24,
    textColor: "#e2e8f0",
    nameColor: "#ffffff",
  },
  decorations: [
    { box: { x: 520, y: 150, width: 4, height: 860 }, shape: "rect", color: "#facc15", opacity: 0.5 },
  ],
  slots: [
    {
      id: "title",
      type: "text",
      box: { x: 60, y: 150, width: 440, height: 90 },
      fontFamily: "Inter",
      maxFontSize: 40,
      minFontSize: 28,
      maxLines: 2,
      align: "left",
      color: "#facc15",
      fontWeight: 800,
      label: "Judul",
      placeholder: "OPEN RECRUITMENT",
    },
    {
      id: "intro",
      type: "text",
      box: { x: 60, y: 250, width: 440, height: 130 },
      fontFamily: "Inter",
      maxFontSize: 28,
      minFontSize: 20,
      maxLines: 3,
      align: "left",
      color: "#e2e8f0",
      fontWeight: 400,
      label: "Kalimat Pembuka",
      placeholder: "Kami sedang mencari talenta terbaik untuk bergabung bersama tim kami.",
    },
    {
      id: "position1",
      type: "text",
      box: { x: 60, y: 400, width: 440, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 30,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#ffffff",
      fontWeight: 600,
      label: "Posisi 1",
      placeholder: "Admin Pelayanan",
    },
    {
      id: "position2",
      type: "text",
      box: { x: 60, y: 465, width: 440, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 30,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#ffffff",
      fontWeight: 600,
      label: "Posisi 2",
      placeholder: "Perawat Pelaksana",
    },
    {
      id: "position3",
      type: "text",
      box: { x: 60, y: 530, width: 440, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 30,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#ffffff",
      fontWeight: 600,
      label: "Posisi 3",
      placeholder: "Staf Kebersihan",
    },
    {
      id: "position4",
      type: "text",
      box: { x: 60, y: 595, width: 440, height: 60 },
      fontFamily: "Inter",
      maxFontSize: 30,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#ffffff",
      fontWeight: 600,
      label: "Posisi 4",
      placeholder: "Satpam",
    },
    {
      id: "cta",
      type: "text",
      box: { x: 60, y: 700, width: 440, height: 80 },
      fontFamily: "Inter",
      maxFontSize: 32,
      minFontSize: 24,
      maxLines: 2,
      align: "left",
      color: "#facc15",
      fontWeight: 700,
      label: "Kontak",
      placeholder: "Kirim CV ke WA 0812-0000-0000",
    },
    {
      id: "photo",
      type: "image",
      box: { x: 560, y: 150, width: 460, height: 860 },
      fit: "contain",
      borderRadius: 24,
      label: "Foto",
    },
  ],
};

export const rekrutmenTemplate: Template = {
  id: "rekrutmen",
  name: "Rekrutmen / Lowongan",
  brand: { ...defaultBrand, backgroundColor: "#0f172a" },
  layouts: {
    "4:5": layout45,
    "1:1": { ...layout45, canvas: { width: 1080, height: 1080 } },
    "9:16": { ...layout45, canvas: { width: 1080, height: 1920 } },
  },
};
