import type { Template, TemplateLayout } from "./types";
import { defaultBrand } from "./brand";

const layout45: TemplateLayout = {
  canvas: { width: 1080, height: 1350 },
  logo: { x: 60, y: 32, size: 40 },
  footerLayout: {
    x: 60,
    y: 1275,
    direction: "row",
    gap: 24,
    iconSize: 52,
    textSize: 29,
    textColor: "#475569",
    nameColor: "#0f172a",
  },
  decorations: [
    {
      box: { x: 10, y: 90, width: 260, height: 260 },
      shape: "text",
      content: "“",
      color: "#e2e8f0",
      fontSize: 260,
      fontWeight: 800,
    },
  ],
  slots: [
    {
      id: "quote",
      type: "text",
      box: { x: 60, y: 210, width: 960, height: 380 },
      fontFamily: "Inter",
      maxFontSize: 52,
      minFontSize: 32,
      maxLines: 5,
      align: "left",
      color: "#0f172a",
      fontWeight: 700,
      label: "Kutipan",
      placeholder: "“Pelayanannya cepat dan ramah, saya jadi pelanggan tetap sejak tahun lalu.”",
    },
    {
      id: "rating",
      type: "text",
      box: { x: 60, y: 610, width: 960, height: 50 },
      fontFamily: "Inter",
      maxFontSize: 32,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#facc15",
      fontWeight: 700,
      label: "Rating",
      placeholder: "★★★★★",
    },
    {
      id: "name",
      type: "text",
      box: { x: 60, y: 670, width: 960, height: 50 },
      fontFamily: "Inter",
      maxFontSize: 32,
      minFontSize: 24,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 700,
      label: "Nama",
      placeholder: "Ibu Sari",
    },
    {
      id: "role",
      type: "text",
      box: { x: 60, y: 720, width: 960, height: 40 },
      fontFamily: "Inter",
      maxFontSize: 26,
      minFontSize: 20,
      maxLines: 1,
      align: "left",
      color: "#64748b",
      fontWeight: 400,
      label: "Peran / Instansi",
      placeholder: "Pelanggan Klinik Sehat Sentosa",
    },
    {
      id: "photo",
      type: "image",
      box: { x: 60, y: 790, width: 200, height: 200 },
      fit: "contain",
      borderRadius: 100,
      label: "Foto",
    },
  ],
};

export const testimoniTemplate: Template = {
  id: "testimoni",
  name: "Testimoni / Review",
  brand: { ...defaultBrand, backgroundColor: "#f8fafc" },
  layouts: {
    "4:5": layout45,
    "1:1": { ...layout45, canvas: { width: 1080, height: 1080 } },
    "9:16": { ...layout45, canvas: { width: 1080, height: 1920 } },
  },
};
