import type { Template } from "./types";
import { defaultBrand } from "./brand";

export const testimoniTemplate: Template = {
  id: "testimoni",
  name: "Testimoni / Review",
  canvas: { width: 1080, height: 1350 },
  brand: { ...defaultBrand, backgroundColor: "#f8fafc" },
  slots: [
    {
      id: "quote",
      type: "text",
      box: { x: 60, y: 200, width: 960, height: 380 },
      fontFamily: "Inter",
      maxFontSize: 48,
      minFontSize: 30,
      maxLines: 5,
      align: "left",
      color: "#0f172a",
      fontWeight: 700,
      label: "Kutipan",
      placeholder: "“Pelayanannya cepat dan ramah, saya jadi pelanggan tetap sejak tahun lalu.”",
    },
    {
      id: "rating",
      type: "text",
      box: { x: 60, y: 600, width: 960, height: 50 },
      fontFamily: "Inter",
      maxFontSize: 28,
      minFontSize: 20,
      maxLines: 1,
      align: "left",
      color: "#facc15",
      fontWeight: 700,
      label: "Rating",
      placeholder: "★★★★★",
    },
    {
      id: "name",
      type: "text",
      box: { x: 60, y: 660, width: 960, height: 50 },
      fontFamily: "Inter",
      maxFontSize: 28,
      minFontSize: 22,
      maxLines: 1,
      align: "left",
      color: "#0f172a",
      fontWeight: 700,
      label: "Nama",
      placeholder: "Ibu Sari",
    },
    {
      id: "role",
      type: "text",
      box: { x: 60, y: 710, width: 960, height: 40 },
      fontFamily: "Inter",
      maxFontSize: 22,
      minFontSize: 18,
      maxLines: 1,
      align: "left",
      color: "#64748b",
      fontWeight: 400,
      label: "Peran / Instansi",
      placeholder: "Pelanggan Klinik Sehat Sentosa",
    },
    {
      id: "photo",
      type: "image",
      box: { x: 60, y: 780, width: 200, height: 200 },
      fit: "cover",
      borderRadius: 100,
      label: "Foto",
      placeholder: "https://...",
    },
  ],
};
